name: Node.js Tests

on:
  push:
    branches:
      - main
      - master

  pull_request:
    branches:
      - main
      - master

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install
        working-directory: backend

      - name: Create .env file
        run: |
          echo JWT_SECRET=testsecret >> .env
          echo MONGO_URI=mongodb://localhost:27017/test >> .env
        working-directory: backend

      - name: Run Jest tests
        run: npm test
        working-directory: backend
